[package]
name = "linfa"
version = "0.3.0"
authors = [
    "Luca Palmieri <rust@lpalmieri.com>",
    "Lorenz Schmidt <bytesnake@mailbox.org>",
    "Paul Körbitz <koerbitz@google.com>"
]
description = "A Machine Learning framework for Rust"
edition = "2018"
license = "MIT/Apache-2.0"

repository = "https://github.com/rust-ml/linfa"
readme = "README.md"

keywords = ["machine-learning", "linfa", "ai", "ml"]
categories = ["algorithms", "mathematics", "science"]

exclude = [".github/"]

[features]
default = []

netlib-static = ["blas", "ndarray-linalg", "netlib-src/static"]
netlib-system = ["blas", "ndarray-linalg", "netlib-src/system"]

openblas-static = ["blas", "ndarray-linalg", "openblas-src/static"]
openblas-system = ["blas", "ndarray-linalg", "openblas-src/system"]

intel-mkl-static = ["blas", "ndarray-linalg", "intel-mkl-src/mkl-static-lp64-seq", "intel-mkl-src/download"]
intel-mkl-system = ["blas", "ndarray-linalg", "intel-mkl-src/mkl-dynamic-lp64-seq"]

blas = ["ndarray/blas"]

[dependencies]
num-traits = "0.2"
rand = { version = "0.7", features = ["small_rng"] }
ndarray = { version = "0.13", default-features = false }
ndarray-linalg = { version = "0.12.1", optional = true }

[dependencies.intel-mkl-src]
version = "0.6.0"
default-features = false
optional = true

[dependencies.netlib-src]
version = "0.8.0"
optional = true
features = ["cblas"]
default-features = false

[dependencies.openblas-src]
version = "0.9.0"
optional = true
default-features = false
features = ["cblas"]

[dev-dependencies]
ndarray-rand = "0.11"
rand_isaac = "0.2"
approx = "0.3"

linfa-datasets = { version = "0.3.0", path = "datasets", features = ["winequality", "iris", "diabetes"] }

[workspace]
members = [
    "linfa-clustering",
    "linfa-reduction",
    "linfa-kernel",
    "linfa-linear",
    "linfa-logistic",
    "linfa-trees",
    "linfa-svm",
    "linfa-hierarchical",
    "linfa-ica",
    "linfa-bayes",
    "linfa-elasticnet",
    "datasets",
]

[profile.release]
opt-level = 3
