[package]
name = "linfa-elastic"
version = "0.1.0"
authors = ["Paul Koerbitz / Google <koerbitz@google.com>"]
edition = "2018"

[dependencies]
ndarray = {version = "0.13", features = ["approx"]}
ndarray-stats = {version = "0.3"}
approx = "0.3"