[package]
name = "linfa-datasets"
version = "0.3.1"
authors = ["Lorenz Schmidt <bytesnake@mailbox.org>"]
description = "Collection of small datasets for Linfa"
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/rust-ml/linfa"

[dependencies]
linfa = { version = "0.3.1", path = ".." }
ndarray = { version = "0.13", default-features = false }
ndarray-csv = "0.4"
csv = "1.1"
flate2 = "1.0"
polars-core = { version = "0.12", default-features = false, optional = true }
polars-io = { version = "0.12", default-features = false, optional = true }

[dev-dependencies]
approx = { version = "0.3", default-features = false, features = ["std"] }

[features]
default = []
diabetes = []
iris = []
winequality = []
linnerud = []
income = ["polars-core", "polars-io", "linfa/polars"]
