[package]
name = "linfa-nn"
version = "0.1.0"
authors = ["YuhanLiin <yuhanliin+github@protonmail.com>"]
edition = "2018"
description = "A collection of nearest neighbour algorithms"
license = "MIT/Apache-2.0"

repository = "https://github.com/rust-ml/linfa/"
readme = "README.md"

keywords = ["nearest-neighbour", "machine-learning", "linfa"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
ndarray = { version = "0.13", features = ["approx"]}
ndarray-rand = "0.11"
ndarray-stats = "0.3"
num-traits = "0.1.32"

linfa = { version = "0.3.1", path = "../.." }

[dev-dependencies]
approx = "0.3"
