[package]
name = "linfa-tsne"
version = "0.3.1"
authors = ["Lorenz Schmidt <lorenz.schmidt@mailbox.org>"]
edition = "2018"

description = "Barnes-Hut t-distributed stochastic neighbor embedding"
license = "MIT/Apache-2.0"

repository = "https://github.com/rust-ml/linfa"
readme = "README.md"

keywords = ["tsne", "data visualization", "clustering", "machine-learning", "linfa"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
ndarray = { version = "0.13", default-features = false }
bhtsne = "0.4.0"

linfa = { version = "0.3.1", path = "../.." }

[dev-dependencies]
rand = "0.7"
ndarray-rand = "0.11"
linfa-datasets = { version = "0.3.1", path = "../../datasets", features = ["iris"] }
linfa-reduction = { version = "0.3.1", path = "../linfa-reduction" }
