on: [push, pull_request]

name: Run iai Benches

jobs:
  testing:
    name: benching
    runs-on: ubuntu-18.04
    if: github.event.pull_request.draft == false
    container:
      image: rustmath/mkl-rust:1.43.0
      options: --security-opt seccomp=unconfined
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Run cargo bench iai
        uses: actions-rs/cargo@v1
        with:
          command: bench
          args: iai --all --features intel-mkl-system
