on: [push, pull_request]

name: Run Tests

jobs:
  testing:
    name: testing
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install ubuntu packages
        run: sudo apt-get install intel-mkl-full

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true

      - name: Run cargo test in release mode
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all --release --features linfa/intel-mkl-system
